language: php

php:
  - 7.2
  - 7.3

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit